# Site settings
title: ModBNSVN - Web Developer
description: "Chuyen mod file Server BNSVN ..."
baseurl: "modbnsvn.github.io"
url: "modbnsvn.github.io"

# User settings
username: Ban Lam De Thuong
user_title: banlamdethuong
email: imhereifyouwant@gmail.com
twitter_username: 
github_username:  
gplus_username:  
linkedin_public_url: 
disqus_username: 
profile_picture:
